### ISSUE TITLE
builder exits, cruise process still up

### ISSUE THREAD

**Issue by piotrmasior** [thoughtworks/cruisecontrol.rb#103]
Hey I encountered  very strange behavior and I am not sure what cause the error. Builder log:

```
[error] /root/.cruise/projects/xxx/work root$ git fetch origin
ssh_exchange_identification: Connection closed by remote host
fatal: The remote end hung up unexpectedly
[]
[error]   /var/cruisecontrol/lib/source_control/abstract_adapter.rb:77:in `rescue in execute_with_error_log'
[error]   /var/cruisecontrol/lib/source_control/abstract_adapter.rb:67:in `execute_with_error_log'
[error]   /var/cruisecontrol/lib/source_control/abstract_adapter.rb:58:in `block in execute_in_local_copy'
[error]   /var/cruisecontrol/lib/source_control/abstract_adapter.rb:57:in `chdir'
[error]   /var/cruisecontrol/lib/source_control/abstract_adapter.rb:57:in `execute_in_local_copy'
[error]   /var/cruisecontrol/lib/source_control/git.rb:114:in `git'
[error]   /var/cruisecontrol/lib/source_control/git.rb:103:in `block in load_new_changesets_from_origin'
[error]   /usr/local/rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/timeout.rb:58:in `timeout'
[error]   /var/cruisecontrol/lib/source_control/git.rb:102:in `load_new_changesets_from_origin'
[error]   /var/cruisecontrol/lib/source_control/git.rb:69:in `new_revisions'
[error]   /var/cruisecontrol/lib/source_control/git.rb:57:in `up_to_date?'
[error]   /var/cruisecontrol/app/models/change_in_source_control_trigger.rb:14:in `build_necessary?'
[error]   /var/cruisecontrol/app/models/project.rb:319:in `block in build_necessary?'
[error]   /var/cruisecontrol/app/models/project.rb:319:in `each'
[error]   /var/cruisecontrol/app/models/project.rb:319:in `any?'
[error]   /var/cruisecontrol/app/models/project.rb:319:in `build_necessary?'
[error]   /var/cruisecontrol/app/models/project.rb:296:in `build_if_necessary'
[error]   /var/cruisecontrol/app/models/polling_scheduler.rb:16:in `run'
[error]   /var/cruisecontrol/script/builder:86:in `block in <top (required)>'
[error]   /var/cruisecontrol/script/builder:85:in `catch'
[error]   /var/cruisecontrol/script/builder:85:in `<top (required)>'
[error]   /var/cruisecontrol/lib/cruise_control/init.rb:92:in `load'
[error]   /var/cruisecontrol/lib/cruise_control/init.rb:92:in `builder'
[error]   /var/cruisecontrol/lib/cruise_control/init.rb:12:in `run'
[error]   /var/cruisecontrol/cruise:10:in `<main>'
[fatal] Input/output error - <STDERR>
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:69:in `write'
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:69:in `puts'
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:69:in `rescue in log_error'
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:66:in `log_error'
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:20:in `rescue in run'
[fatal]   /var/cruisecontrol/app/models/polling_scheduler.rb:15:in `run'
[fatal]   /var/cruisecontrol/script/builder:86:in `block in <top (required)>'
[fatal]   /var/cruisecontrol/script/builder:85:in `catch'
[fatal]   /var/cruisecontrol/script/builder:85:in `<top (required)>'
[fatal]   /var/cruisecontrol/lib/cruise_control/init.rb:92:in `load'
[fatal]   /var/cruisecontrol/lib/cruise_control/init.rb:92:in `builder'
[fatal]   /var/cruisecontrol/lib/cruise_control/init.rb:12:in `run'
[fatal]   /var/cruisecontrol/cruise:10:in `<main>'
[info]  [2012-06-28 18:20:02] Builder for project 'xxx' exited
```

note: when I started cruise via:

```
./cruise start --daemon
```

everything works perfectly a few hours... and after that occasional error builder process is killed

env:

```
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.24
  - RUBY VERSION: 1.9.2 (2012-02-14 patchlevel 318) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-1.9.2-p318@xxx
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-1.9.2-p318/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-1.9.2-p318@xxx/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux

CentOs 5
rails (3.0.7)
```

**Comment by seanmarcia** [comment]
Sorry for the slow response, I only recently got access to the project and with the help of a few others are in the process of triage. Since it has been so long I'm closing this but if this is still an issue let me know!
